services:
  oracle-data-provider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-data-provider
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped